version: '3.8'

services:
 web:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - 5000:5000
   develop:
     watch:
       - path: ./requirements.txt
         action: rebuild
       - path: ./Dockerfile
         action: rebuild
       - path: .
         target: /app
         action: sync

volumes:
 tasked:
